version: '3'
services:
  mnist:
    image: mnist
    ports:
      - "9000:9000"
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  metrics-and-scale:
    image: mas
    depends_on:
      - prometheus
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
