version: '3.1'
    
services:
  application:
    image: application
    ports:
      - "8082:8082"
      - "8000:8000"

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  
  load-balancer:
    image: load-balancer
    volumes:
      - ~/tutorial/Application_v_1/plots:/plots
      - ~/tutorial/Application_v_1/QSavedWeights:/QSavedWeights
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints:
          - node.role == manager

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus