version: '3.8'
    
services:
  application:
    image: application-mnistdocker
    ports:
      - "8082:8082"
      - "8501:8501"

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
  
  load-balancer:
    image: load-balancer
    volumes:
      - ~/tutorial/Application_v_1/plots:/plots
      - ~/tutorial/Application_v_1/QSavedWeights:/QSavedWeights
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - application

  produce-load:
    image: produce-load
    depends_on:
      - application

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - application