version: '3'
services:
  application:
    image: application
    ports:
      - "8082:8082"
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  metrics-and-scale:
    image: metrics-and-scaler
    depends_on:
      - prometheus
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus