global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'swarm-service'
    dns_sd_configs:
      - names:
          - 'tasks.application'
        type: 'A'
        port: 8000
    metrics_path: '/actuator/prometheus'

#global:
#  scrape_interval: 15s
#  evaluation_interval: 15s
#
#scrape_configs:
#  - job_name: 'application'
#    static_configs:
#      - targets: ['application:8000']
#  - job_name: 'swarm-service'
#      dns_sd_configs:
#        - names:
#            - 'tasks.application'
#          type: 'A'
#          port: 8000
#      metrics_path: '/actuator/prometheus'
#
